name: '1003'
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py311h6b1f9c4_0
  - blosc=1.21.6=he440d0b_1
  - brotli-python=1.2.0=py311h66f275b_1
  - brunsli=0.1=hd1e3526_2
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - c-blosc2=2.22.0=hc31b594_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cdsapi=0.7.7=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cftime=1.6.5=py311h0372a8f_1
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cpython=3.11.14=py311hd8ed1ab_3
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cusparselt=0.7.0.0=hcd2ec93_0
  - dav1d=1.2.1=hd590300_0
  - ecmwf-datastores-client=0.4.2=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_2
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h19486de_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2026.1.14=py311h273f733_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.22.2=ha1258a1_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.5=h088129d_0
  - libavif16=1.3.0=h316e467_3
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.18.0=hcf29cc6_1
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgomp=15.2.0=he0feb66_16
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.2=ha09017c_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h566cb83_2
  - libnetcdf=4.9.3=nompi_hbf2fc22_104
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.9.86=hecca717_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.55=h421ea60_0
  - libprotobuf=5.28.3=h6128344_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=259.1=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.6.0=cuda126_generic_h4a15719_200
  - libudev1=259.1=h6569c3e_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multiurl=0.3.7=pyhd8ed1ab_0
  - nccl=2.29.3.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.4=nompi_py311h66524b1_102
  - networkx=3.6.1=pyhcf101f3_0
  - nomkl=1.0=h5ca1d4c_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.26.0=h8d634f6_0
  - openssl=3.6.1=h35e630c_1
  - optree=0.18.0=py311hdf67eae_0
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=3.0.2=pyh7a1b43c_0
  - pybind11-global=3.0.2=pyhc7ab6ef_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pytorch=2.6.0=cuda126_generic_py311_he5f81b5_200
  - pytz=2025.2=pyhd8ed1ab_0
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=61.0=h192683f_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-image=0.26.0=np2py311h2a99c40_0
  - scikit-learn=1.8.0=np2py311ha15b03d_1
  - scipy=1.17.0=py311hbe70eeb_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - svt-av1=4.0.0=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2026.1.28=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - zfp=1.0.1=h909a3a2_5
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - anyio==4.12.0
      - chronos-forecasting==2.2.2
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - einops==0.8.2
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - numpy==2.4.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - packaging==25.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.1.0
      - psutil==7.2.2
      - pyparsing==3.3.1
      - pyyaml==6.0.3
      - regex==2025.11.3
      - safetensors==0.7.0
      - shellingham==1.5.4
      - statsmodels==0.14.6
      - timesfm==2.0.0
      - tokenizers==0.22.2
      - torch==2.7.1+cu118
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.3.1
      - typer-slim==0.21.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - uv==0.9.22
prefix: /home/quentin/miniforge3/envs/1003
